const labels = { new: 'Neu', in_progress: 'In Bearbeitung', completed: 'Abgeschlossen', quarantine: 'Quarantäne', approved: 'Freigegeben', rejected: 'Abgelehnt' };
const text = (tag, value, className = '') => { const node = document.createElement(tag); if (className) node.className = className; node.textContent = value ?? ''; return node; };
const button = (label, onClick, className = '') => { const node = text('button', label, `btn ${className}`); node.type = 'button'; node.addEventListener('click', onClick); return node; };
const badge = (value) => text('span', labels[value] || value, `badge ${value}`);
const statusBadge = (value) => badge(value);

export function createInternalApp({ root, fetchImpl = fetch, uuid = () => crypto.randomUUID() }) {
  let view = 'list'; let selected = null; let query = ''; let status = ''; let page = 1; const mutationStates = new Map();
  const stateFor = (leadId) => { if (!mutationStates.has(String(leadId))) mutationStates.set(String(leadId), { uncertain: false, uiError: '', lastMutation: null }); return mutationStates.get(String(leadId)); };
  const api = async (url, options) => { const response = await fetchImpl(url, options); const body = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(body.error || 'request_failed'); error.status = response.status; error.body = body; throw error; } return body; };
  const clear = () => root.replaceChildren();
  const renderState = (title, message, action) => { clear(); const section = text('section', '', 'state'); section.append(text('span', 'INTERNER ARBEITSBEREICH', 'kicker'), text('h1', title), text('p', message)); if (action) section.append(button(action.label, action.onClick, 'primary')); root.append(section); };
  const renderList = async () => {
    renderState('Anfragen werden geladen.', 'Die Übersicht wird vorbereitet …');
    try {
      const params = new URLSearchParams({ page: String(page) }); if (query) params.set('q', query); if (status) params.set('status', status);
      const data = await api(`/internal/api/leads?${params}`); clear();
      const heading = text('div', '', 'heading'); const copy = text('div'); copy.append(text('span', 'TECHNISCHE ANFRAGEN', 'kicker'), text('h1', 'Anfragen'), text('p', 'Anfragen prüfen, Dateien sichten und den nächsten Schritt festhalten.', 'lead-copy')); heading.append(copy, button('Aktualisieren', () => renderList())); root.append(heading);
      const panel = text('section', '', 'panel'); const toolbar = text('div', '', 'toolbar'); const searchLabel = text('label', 'Firma, Kontakt oder E-Mail suchen'); const search = document.createElement('input'); search.type = 'search'; search.value = query; search.setAttribute('aria-label', 'Anfragen durchsuchen'); search.addEventListener('input', () => { query = search.value; }); search.addEventListener('change', () => { page = 1; renderList(); }); searchLabel.append(search); const filterLabel = text('label', 'Status'); const filter = document.createElement('select'); [['', 'Alle Status'], ['new', 'Neu'], ['in_progress', 'In Bearbeitung'], ['completed', 'Abgeschlossen']].forEach(([value, label]) => { const option = text('option', label); option.value = value; option.selected = value === status; filter.append(option); }); filter.addEventListener('change', () => { status = filter.value; page = 1; renderList(); }); filterLabel.append(filter); toolbar.append(searchLabel, filterLabel); panel.append(toolbar);
      const list = text('div'); if (!data.items.length) list.append(text('div', 'Keine Anfragen gefunden.', 'empty')); data.items.forEach((item) => { const row = button('', () => { selected = item.id; view = 'detail'; history.pushState({ internalLeadId: item.id }, '', `/internal/?lead=${encodeURIComponent(item.id)}`); renderDetail(); }, 'lead-row'); const main = text('span', '', 'lead-main'); main.append(text('strong', `#${item.id} · ${item.company}`), text('span', item.name, 'lead-sub')); row.append(main, statusBadge(item.workflow_status), text('span', `${item.file_count} ${item.file_count === 1 ? 'Datei' : 'Dateien'}`, 'files'), text('span', new Date(item.created_at).toLocaleString('de-DE', { dateStyle: 'medium', timeStyle: 'short' }), 'date'), text('span', '›')); list.append(row); }); panel.append(list); if (page > 1 || data.has_more) { const pagination = text('nav', '', 'pagination'); pagination.setAttribute('aria-label', 'Seitennavigation'); const previous = button('Vorherige Seite', () => { page -= 1; renderList(); }); previous.disabled = page <= 1; const next = button('Nächste Seite', () => { page += 1; renderList(); }); next.disabled = !data.has_more; pagination.append(previous, text('span', `Seite ${page}`), next); panel.append(pagination); } root.append(panel);
    } catch (error) { renderState('Verbindung unterbrochen.', 'Die Übersicht ist momentan nicht verfügbar.', { label: 'Erneut versuchen', onClick: renderList }); }
  };
  const renderDetail = async () => {
    renderState('Anfrage wird geladen.', 'Die Details werden vorbereitet …');
    try {
      const detail = await api(`/internal/api/leads/${encodeURIComponent(selected)}`); const mutation = stateFor(detail.id); clear(); const back = button('← Alle Anfragen', () => { history.pushState({}, '', '/internal/'); view = 'list'; selected = null; renderList(); }, 'back'); root.append(back);
      if (mutation.uncertain || mutation.uiError) { const alert = text('div', mutation.uiError || 'Die Aktion konnte nicht bestätigt werden. Bitte laden Sie den aktuellen Stand.', 'alert'); alert.setAttribute('role', 'alert'); alert.append(button('Aktuellen Stand laden', () => { mutation.uncertain = false; mutation.uiError = ''; mutation.lastMutation = null; renderDetail(); })); root.append(alert); }
      const heading = text('div', '', 'heading detail-head'); const title = text('div'); title.append(text('span', `ANFRAGE #${detail.id} · ${detail.company}`, 'kicker'), text('h1', detail.service || 'Anfrage'), text('div', '', 'detail-meta')); title.lastChild.append(statusBadge(detail.workflow_status), text('span', ' · Eingang ' + new Date(detail.created_at).toLocaleString('de-DE'))); const actionButton = button(detail.workflow_status === 'completed' ? 'Wieder öffnen' : 'Status ändern', () => openStatusDialog(detail), 'primary'); actionButton.disabled = mutation.uncertain; heading.append(title, actionButton); root.append(heading);
      const grid = text('div', '', 'grid'); const main = text('div'); const message = text('section', '', 'card'); const messageTitle = text('div', '', 'card-title'); messageTitle.append(text('h2', 'Anfrage im Wortlaut'), text('span', detail.language || '', 'kicker')); message.append(messageTitle, text('p', detail.message || 'Keine Nachricht übermittelt.')); main.append(message); const files = text('section', '', 'card'); const filesTitle = text('div', '', 'card-title'); filesTitle.append(text('h2', 'Technische Dateien'), text('span', `${detail.uploads.length} ${detail.uploads.length === 1 ? 'Datei' : 'Dateien'}`, 'kicker')); files.append(filesTitle); if (!detail.uploads.length) files.append(text('p', 'Zu dieser Anfrage wurden keine Dateien übermittelt.')); detail.uploads.forEach((file) => { const card = text('article', '', 'file'); card.append(text('strong', file.original_name), text('div', `${file.extension.toUpperCase()} · ${file.byte_size} Bytes`, 'file-meta'), statusBadge(file.security_status)); const actions = text('div', '', 'actions'); if (file.allowed_actions.includes('download')) actions.append(button('Download', () => openDownloadDialog(file))); if (file.allowed_actions.includes('approve')) actions.append(button('Freigeben', () => openReviewDialog(file, 'approve'), 'primary'), button('Ablehnen', () => openReviewDialog(file, 'reject'), 'danger')); card.append(actions); files.append(card); }); main.append(files); grid.append(main);
      const side = text('aside'); const contact = text('section', '', 'card'); contact.append(text('h2', 'Kontakt & Kontext'), text('p', detail.name), text('p', detail.email), text('p', detail.phone || '')); side.append(contact); const timeline = text('section', '', 'card'); timeline.append(text('h2', 'Verlauf')); detail.events.forEach((event) => timeline.append(text('p', event.type === 'received' ? `Anfrage eingegangen · ${new Date(event.occurred_at).toLocaleString('de-DE')}` : `${labels[event.from_status]} → ${labels[event.to_status]} · Version ${event.from_version} → ${event.to_version}`))); side.append(timeline); grid.append(side); root.append(grid);
    } catch { renderState('Anfrage nicht verfügbar.', 'Die Anfrage konnte nicht geladen werden.', { label: 'Erneut versuchen', onClick: renderDetail }); }
  };
  const dialog = (title, body, submitLabel, submit) => { const node = document.createElement('dialog'); node.className = 'dialog'; const content = text('div', '', 'dialog-content'); content.append(text('h2', title)); content.append(body); const actions = text('div', '', 'dialog-actions'); const submitButton = button(submitLabel, async () => { if (submitButton.disabled) return; submitButton.disabled = true; try { await submit(node); } finally { submitButton.disabled = false; } }, 'primary'); actions.append(button('Abbrechen', () => node.close()), submitButton); content.append(actions); node.append(content); document.body.append(node); node.addEventListener('close', () => node.remove(), { once: true }); node.showModal(); };
  const openStatusDialog = (detail) => { const allowedTargets = { new: [['in_progress', 'In Bearbeitung'], ['completed', 'Abgeschlossen']], in_progress: [['completed', 'Abgeschlossen']], completed: [['in_progress', 'Wieder öffnen']] }; const select = document.createElement('select'); (allowedTargets[detail.workflow_status] || []).forEach(([value, label]) => { const option = text('option', label); option.value = value; select.append(option); }); const body = text('div'); body.append(text('p', 'Der Wechsel wird mit Versionsprüfung und Auditbeleg gespeichert.'), select); dialog('Status ändern', body, 'Übernehmen', async (node) => { await mutateStatus(detail, select.value); node.close(); }); };
  const openReviewDialog = (file, action) => { const body = text('div'); if (action === 'reject') { body.append(text('p', 'Interne Entscheidung. Es wird keine Kunden-E-Mail versendet.')); const reason = document.createElement('textarea'); reason.required = true; reason.maxLength = 200; reason.placeholder = 'Ablehnungsgrund'; body.append(reason); dialog('Datei ablehnen', body, 'Datei ablehnen', async (node) => { if (!reason.value.trim()) { reason.focus(); return; } await mutateReview(file, action, reason.value); node.close(); }); } else { body.append(text('p', 'Die Freigabe bestätigt keine Malwarefreiheit.')); dialog('Datei freigeben', body, 'Datei freigeben', async (node) => { await mutateReview(file, action); node.close(); }); } };
  const openDownloadDialog = (file) => { const leadId = selected; const body = text('div'); body.append(text('p', file.security_status === 'rejected' ? 'Diese Datei wurde abgelehnt und darf nicht als freigegebene Fertigungsgrundlage verwendet werden.' : 'Geschützter Mitarbeiterabruf.')); dialog('Datei herunterladen', body, 'Download', async (node) => { try { const response = await fetchImpl(`/internal/leads/${leadId}/uploads/${file.id}`); if (!response.ok) { const error = new Error('download_failed'); error.status = response.status; throw error; } const blob = await response.blob(); const href = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = href; link.download = file.original_name; link.hidden = true; document.body.append(link); link.click(); link.remove(); URL.revokeObjectURL(href); if (node.open) node.close(); } catch (error) { stateFor(leadId).uiError = error.status === 401 ? 'Die Anmeldung ist abgelaufen. Bitte melden Sie sich erneut an.' : 'Der Download konnte nicht gestartet werden.'; if (node.open) node.close(); if (String(selected) === String(leadId)) renderDetail(); } }); };
  const mutateStatus = async (detail, target) => { const mutation = stateFor(detail.id); mutation.lastMutation ||= { requestId: uuid(), leadId: detail.id }; try { await api(`/internal/api/leads/${detail.id}/status`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin }, body: JSON.stringify({ request_id: mutation.lastMutation.requestId, expected_status: detail.workflow_status, expected_version: detail.workflow_version, target_status: target }) }); mutation.uncertain = false; mutation.uiError = ''; mutation.lastMutation = null; renderDetail(); } catch (error) { mutation.uncertain = true; mutation.uiError = error.status === 401 ? 'Die Anmeldung ist abgelaufen. Bitte melden Sie sich erneut an.' : error.status === 409 ? 'Der Stand hat sich geändert. Bitte laden Sie den aktuellen Stand.' : 'Die Aktion konnte nicht bestätigt werden. Bitte laden Sie den aktuellen Stand.'; renderDetail(); } };
  const mutateReview = async (file, action, reason) => { const mutation = stateFor(selected); try { await api(`/internal/leads/${selected}/uploads/${file.id}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json', origin: location.origin }, body: JSON.stringify(action === 'reject' ? { reason } : {}) }); mutation.uiError = ''; renderDetail(); } catch (error) { mutation.uiError = error.status === 401 ? 'Die Anmeldung ist abgelaufen. Bitte melden Sie sich erneut an.' : error.status === 409 ? 'Die Datei wurde inzwischen geändert. Bitte laden Sie den aktuellen Stand.' : 'Die Dateiaktion konnte nicht bestätigt werden.'; mutation.uncertain = error.status === 401 || error.status === 409; renderDetail(); } };
  const onPopState = () => { const lead = new URLSearchParams(location.search).get('lead'); if (lead) { selected = lead; view = 'detail'; renderDetail(); } else { selected = null; view = 'list'; renderList(); } };
  window.addEventListener('popstate', onPopState);
  renderList(); return { refresh: renderList, open: (id) => { selected = id; history.pushState({ internalLeadId: id }, '', `/internal/?lead=${encodeURIComponent(id)}`); renderDetail(); }, destroy: () => { window.removeEventListener('popstate', onPopState); root.replaceChildren(); } };
}

if (typeof document !== 'undefined') { const root = document.querySelector('#internal-app'); if (root) createInternalApp({ root }); }
